insert into public.exam_questions (
    question_type,
    module,
    category,
    difficulty,
    question_text,
    option_a,
    option_b,
    option_c,
    option_d,
    correct_option,
    explanation,
    legal_source,
    legal_article,
    legal_reference
)
values
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Cuando otro actor vial comete un error que pone en riesgo la circulación, considero adecuado:',
    'Responder agresivamente para demostrarle su error.',
    'Mantener la calma y adoptar una conducta preventiva.',
    'Aumentar la velocidad para alejarme rápidamente.',
    'Usar la bocina de manera insistente para intimidarlo.',
    'B',
    'La conducción segura exige autocontrol y prevención frente a situaciones de riesgo.',
    'Enfoque de seguridad vial',
    'Conducta segura',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Si estoy cansado y considero que mi capacidad de conducción está disminuida, debo:',
    'Continuar porque conozco la vía.',
    'Conducir más rápido para llegar antes.',
    'Evitar conducir hasta encontrarme en condiciones adecuadas.',
    'Tomar riesgos únicamente en vías despejadas.',
    'C',
    'La conducción debe realizarse en condiciones que permitan mantener el control y una atención adecuada.',
    'Seguridad vial',
    'Conducta preventiva',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Ante un peatón que cruza correctamente por un lugar destinado para ello, mi conducta debe ser:',
    'Acelerar para pasar antes.',
    'Reducir la velocidad y darle prioridad cuando corresponda.',
    'Usar la bocina para obligarlo a detenerse.',
    'Pasar por un lado sin reducir la velocidad.',
    'B',
    'Los usuarios vulnerables requieren especial atención y una conducción preventiva.',
    'Seguridad vial',
    'Usuarios vulnerables',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Si otro motociclista circula de manera imprudente, considero adecuado:',
    'Imitar su comportamiento.',
    'Competir con él.',
    'Mantener mi conducción segura sin asumir su conducta.',
    'Seguirlo para reclamarle.',
    'C',
    'La conducta de otros usuarios no justifica asumir comportamientos de riesgo.',
    'Seguridad vial',
    'Conducta preventiva',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'medium',
    'Cuando las condiciones climáticas reducen la visibilidad, debo:',
    'Mantener la misma velocidad.',
    'Aumentar la velocidad para abandonar la zona.',
    'Adaptar la conducción a las condiciones existentes.',
    'Conducir únicamente por el centro de la vía.',
    'C',
    'La velocidad y conducción deben adaptarse a las condiciones de la vía y del entorno.',
    'Seguridad vial',
    'Conducción preventiva',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Usar elementos de protección para conducir motocicleta es:',
    'Una conducta que depende únicamente de la experiencia.',
    'Una medida preventiva de seguridad.',
    'Necesario solamente en carretera.',
    'Opcional cuando el trayecto es corto.',
    'B',
    'Los elementos de protección reducen la exposición al riesgo durante la conducción.',
    'Seguridad vial',
    'Protección del motociclista',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'medium',
    'Si debo realizar una maniobra y existe duda sobre si es segura, debo:',
    'Realizarla rápidamente.',
    'Esperar y verificar que pueda ejecutarse de forma segura.',
    'Acelerar para ganar espacio.',
    'Confiar únicamente en la reacción de los demás.',
    'B',
    'La conducción preventiva prioriza verificar las condiciones antes de ejecutar una maniobra.',
    'Seguridad vial',
    'Conducción preventiva',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Considero importante respetar las normas de tránsito aunque no exista presencia visible de una autoridad porque:',
    'Las normas solo son obligatorias cuando hay vigilancia.',
    'La seguridad vial depende del cumplimiento permanente de las normas.',
    'Las normas solamente aplican a vehículos particulares.',
    'La vigilancia determina cuándo deben cumplirse.',
    'B',
    'El cumplimiento de las normas es permanente y contribuye a la seguridad de todos los usuarios.',
    'Ley 769 de 2002',
    'Artículo 109',
    'Código Nacional de Tránsito'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'medium',
    'Ante una situación de tráfico que genera estrés, considero más seguro:',
    'Tomar decisiones impulsivas.',
    'Mantener el control emocional y conducir preventivamente.',
    'Responder a otros conductores.',
    'Aumentar la velocidad.',
    'B',
    'El autocontrol favorece decisiones seguras durante la conducción.',
    'Seguridad vial',
    'Conducta preventiva',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Cuando transporto un acompañante en motocicleta, debo:',
    'Ignorar las condiciones del acompañante.',
    'Adoptar una conducción segura considerando el riesgo adicional.',
    'Aumentar la velocidad.',
    'Realizar maniobras más rápidas.',
    'B',
    'El transporte de un pasajero requiere conducción estable y preventiva.',
    'Seguridad vial',
    'Motocicletas',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'medium',
    'Si observo una situación peligrosa en la vía, mi primera prioridad debe ser:',
    'Demostrar que tengo prioridad.',
    'Proteger la vida y evitar aumentar el riesgo.',
    'Avanzar rápidamente.',
    'Ignorar la situación.',
    'B',
    'La seguridad de los actores viales debe prevalecer frente a la intención de continuar la marcha.',
    'Seguridad vial',
    'Sistema seguro',
    'Referencia formativa ANSV'
),
(
    'attitude',
    'attitudes',
    ARRAY['A2'],
    'easy',
    'Una conducción responsable implica:',
    'Asumir riesgos cuando se tiene experiencia.',
    'Anticiparse a situaciones peligrosas y actuar preventivamente.',
    'Conducir siempre al límite máximo permitido.',
    'Priorizar llegar rápidamente.',
    'B',
    'La conducción preventiva busca anticipar y reducir los riesgos.',
    'Seguridad vial',
    'Conducción preventiva',
    'Referencia formativa ANSV'
),

(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Cuál es el propósito principal de una movilidad segura?',
    'Aumentar la velocidad promedio.',
    'Reducir los riesgos de lesiones y muertes en la vía.',
    'Eliminar las señales de tránsito.',
    'Priorizar únicamente a los vehículos.',
    'B',
    'La seguridad vial busca proteger la vida y reducir las consecuencias de los siniestros.',
    'Seguridad vial',
    'Sistema seguro',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Cuál de los siguientes es un actor vial vulnerable?',
    'Peatón.',
    'Semáforo.',
    'Señal vertical.',
    'Pavimento.',
    'A',
    'Los peatones son usuarios especialmente vulnerables frente a vehículos.',
    'Seguridad vial',
    'Actores viales',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'medium',
    'Una conducta preventiva al aproximarse a una intersección consiste en:',
    'Acelerar sin observar.',
    'Reducir la atención porque existe señalización.',
    'Observar el entorno y anticipar posibles conflictos.',
    'Conducir ocupando cualquier carril.',
    'C',
    'La anticipación permite identificar riesgos antes de ingresar a la intersección.',
    'Seguridad vial',
    'Conducción preventiva',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'easy',
    'Cuando la vía presenta condiciones adversas, el conductor debe:',
    'Adaptar su conducción.',
    'Mantener siempre la velocidad máxima.',
    'Acelerar.',
    'Ignorar las condiciones.',
    'A',
    'La conducción debe adaptarse a las condiciones reales de circulación.',
    'Ley 769 de 2002',
    'Artículos 106 y 107',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'medium',
    '¿Cuál es una característica de una conducción defensiva?',
    'Anticipar posibles errores de otros usuarios.',
    'Confiar exclusivamente en la prioridad.',
    'Conducir siempre rápidamente.',
    'No observar los espejos.',
    'A',
    'La conducción defensiva considera que otros usuarios pueden cometer errores.',
    'Seguridad vial',
    'Conducción defensiva',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'easy',
    'En una motocicleta, el uso adecuado del casco tiene como finalidad principal:',
    'Mejorar la velocidad.',
    'Reducir el riesgo de lesiones en la cabeza.',
    'Aumentar el consumo de combustible.',
    'Evitar todas las sanciones.',
    'B',
    'El casco es un elemento fundamental de protección para el motociclista.',
    'Ley 769 de 2002',
    'Artículo 94',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'medium',
    'Al aproximarse a una zona escolar, el conductor debe:',
    'Aumentar la velocidad.',
    'Extremar las precauciones y adaptar la velocidad.',
    'Usar permanentemente la bocina.',
    'Ignorar a los peatones.',
    'B',
    'Las zonas escolares requieren especial precaución por la presencia de usuarios vulnerables.',
    'Ley 769 de 2002',
    'Artículo 106',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Qué debe hacer un conductor ante una situación que pueda generar un siniestro?',
    'Aumentar la velocidad.',
    'Adoptar medidas para reducir el riesgo.',
    'Cerrar los ojos y continuar.',
    'Ignorarla.',
    'B',
    'La conducción segura requiere identificar y gestionar los riesgos.',
    'Seguridad vial',
    'Sistema seguro',
    'Referencia ANSV'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'easy',
    'La movilidad sostenible busca, entre otros objetivos:',
    'Promover desplazamientos eficientes y reducir impactos negativos.',
    'Eliminar el transporte público.',
    'Aumentar el consumo de combustible.',
    'Priorizar vehículos de mayor tamaño.',
    'A',
    'La movilidad sostenible considera eficiencia, ambiente y seguridad.',
    'Movilidad sostenible',
    'Formación vial',
    'Referencia ANSV'
),
(
    'knowledge',
    'safe_mobility',
    ARRAY['A2','B1','C1'],
    'medium',
    '¿Qué factor debe considerar un conductor al elegir una velocidad segura?',
    'Solamente la potencia del vehículo.',
    'Las condiciones de la vía, el entorno y los usuarios.',
    'Solamente la experiencia del conductor.',
    'Únicamente el límite máximo.',
    'B',
    'La velocidad segura debe considerar las condiciones reales de circulación.',
    'Ley 769 de 2002',
    'Artículos 106 y 107',
    'Código Nacional de Tránsito'
),

(
    'knowledge',
    'traffic_rules',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Qué norma establece el Código Nacional de Tránsito Terrestre en Colombia?',
    'Ley 769 de 2002.',
    'Ley 100 de 1993.',
    'Ley 80 de 1993.',
    'Ley 1437 de 2011.',
    'A',
    'La Ley 769 de 2002 expide el Código Nacional de Tránsito Terrestre.',
    'Ley 769 de 2002',
    'Ley 769 de 2002',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'traffic_rules',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Qué debe hacer un conductor frente a una señal de tránsito?',
    'Obedecerla conforme a las normas.',
    'Ignorarla si no hay autoridad.',
    'Obedecerla únicamente de noche.',
    'Decidir libremente si la cumple.',
    'A',
    'Los usuarios de la vía están obligados a obedecer las señales de tránsito.',
    'Ley 769 de 2002',
    'Artículo 109',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'traffic_rules',
    ARRAY['A2','B1','C1'],
    'medium',
    'En una vía urbana, la velocidad máxima general no puede superar:',
    '30 km/h en todas las vías.',
    '50 km/h, salvo las condiciones y excepciones previstas legalmente.',
    '90 km/h en todas las vías.',
    '120 km/h.',
    'B',
    'El artículo 106 establece el límite general de 50 km/h para vías urbanas, con condiciones específicas y excepciones previstas en la norma.',
    'Ley 769 de 2002 modificada por Ley 2251 de 2022',
    'Artículo 106',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'traffic_rules',
    ARRAY['A2','B1','C1'],
    'medium',
    'En zonas escolares y residenciales, la velocidad debe ser:',
    'Hasta 30 km/h.',
    'Hasta 90 km/h.',
    'Hasta 120 km/h.',
    'Sin límite.',
    'A',
    'La norma establece hasta 30 km/h para zonas escolares y residenciales.',
    'Ley 769 de 2002 modificada por Ley 2251 de 2022',
    'Artículo 106',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'traffic_rules',
    ARRAY['A2','B1','C1'],
    'medium',
    'En carreteras nacionales y departamentales, para vehículos públicos o privados, la velocidad no puede superar:',
    '50 km/h.',
    '70 km/h.',
    '90 km/h, salvo la excepción legal para determinadas vías doble calzada.',
    '150 km/h.',
    'C',
    'El artículo 107 establece 90 km/h como límite general y contempla una excepción de hasta 120 km/h en determinadas vías doble calzada sin pasos peatonales.',
    'Ley 769 de 2002 modificada por Ley 2251 de 2022',
    'Artículo 107',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'traffic_rules',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Quién debe obedecer las señales de tránsito?',
    'Solamente los conductores.',
    'Todos los usuarios de la vía.',
    'Solamente los peatones.',
    'Solamente los motociclistas.',
    'B',
    'El artículo 109 establece la obligatoriedad para todos los usuarios de la vía.',
    'Ley 769 de 2002',
    'Artículo 109',
    'Código Nacional de Tránsito'
),

(
    'knowledge',
    'signage_infrastructure',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Cuál es el objetivo de una señal reglamentaria?',
    'Advertir un peligro.',
    'Indicar limitaciones, prohibiciones o restricciones.',
    'Identificar únicamente destinos turísticos.',
    'Informar sobre el clima.',
    'B',
    'Las señales reglamentarias indican limitaciones, prohibiciones o restricciones.',
    'Ley 769 de 2002',
    'Artículo 110',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'signage_infrastructure',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Cuál es la función principal de una señal preventiva?',
    'Advertir sobre la existencia de un peligro.',
    'Imponer una sanción.',
    'Identificar documentos.',
    'Registrar vehículos.',
    'A',
    'Las señales preventivas advierten sobre peligros y su naturaleza.',
    'Ley 769 de 2002',
    'Artículo 110',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'signage_infrastructure',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Qué función cumplen las señales informativas?',
    'Identificar vías y orientar al usuario.',
    'Imponer restricciones.',
    'Ordenar detener todos los vehículos.',
    'Sancionar automáticamente.',
    'A',
    'Las señales informativas identifican vías y orientan a los usuarios.',
    'Ley 769 de 2002',
    'Artículo 110',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'signage_infrastructure',
    ARRAY['A2','B1','C1'],
    'easy',
    '¿Qué característica tienen las señales transitorias?',
    'Son de color naranja y modifican temporalmente el régimen normal de la vía.',
    'Son exclusivamente azules.',
    'Solo se utilizan en parqueaderos.',
    'No tienen carácter vial.',
    'A',
    'El artículo 110 establece su carácter temporal y color naranja.',
    'Ley 769 de 2002',
    'Artículo 110',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'signage_infrastructure',
    ARRAY['A2','B1','C1'],
    'medium',
    'Si una señal de tránsito indica una restricción, el conductor debe:',
    'Cumplirla.',
    'Ignorarla si conoce la vía.',
    'Cumplirla únicamente cuando haya policía.',
    'Decidir si le resulta conveniente.',
    'A',
    'Las señales de tránsito son de obligatorio cumplimiento.',
    'Ley 769 de 2002',
    'Artículos 109 y 110',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'signage_infrastructure',
    ARRAY['A2','B1','C1'],
    'easy',
    'Las señales transitorias pueden ser:',
    'Solamente informativas.',
    'Reglamentarias, preventivas o informativas.',
    'Solamente reglamentarias.',
    'Solamente preventivas.',
    'B',
    'La Ley 769 contempla que las señales transitorias pueden cumplir cualquiera de esas funciones.',
    'Ley 769 de 2002',
    'Artículo 110',
    'Código Nacional de Tránsito'
),

(
    'knowledge',
    'vehicle',
    ARRAY['A2'],
    'easy',
    'Antes de conducir una motocicleta, el conductor debe:',
    'Verificar las condiciones básicas de seguridad del vehículo.',
    'Ignorar el estado de las llantas.',
    'Conducir inmediatamente.',
    'Revisar únicamente el combustible.',
    'A',
    'La revisión preventiva permite detectar condiciones que puedan comprometer la seguridad.',
    'Seguridad vial',
    'Revisión preventiva',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'vehicle',
    ARRAY['A2'],
    'easy',
    'En una motocicleta, los sistemas de freno deben:',
    'Encontrarse en condiciones adecuadas de funcionamiento.',
    'Utilizarse solamente en emergencias.',
    'Estar parcialmente dañados.',
    'Revisarse únicamente una vez al año.',
    'A',
    'El sistema de frenos es un elemento esencial para el control seguro de la motocicleta.',
    'Seguridad vial',
    'Sistemas de seguridad',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'vehicle',
    ARRAY['A2'],
    'medium',
    'Las llantas de una motocicleta deben mantenerse:',
    'Con presión y estado adecuados según las especificaciones del fabricante.',
    'Siempre completamente desinfladas.',
    'Con desgaste extremo.',
    'Sin importar su estado.',
    'A',
    'Las condiciones de las llantas influyen directamente en estabilidad y frenado.',
    'Seguridad vial',
    'Mantenimiento preventivo',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'vehicle',
    ARRAY['A2'],
    'easy',
    '¿Cuál es una función de las luces y dispositivos luminosos de la motocicleta?',
    'Permitir ser visto y comunicar determinadas maniobras.',
    'Aumentar la potencia del motor.',
    'Reducir el peso.',
    'Sustituir los frenos.',
    'A',
    'Los dispositivos luminosos contribuyen a la visibilidad y comunicación con otros usuarios.',
    'Ley 769 de 2002',
    'Artículo 94',
    'Código Nacional de Tránsito'
),
(
    'knowledge',
    'vehicle',
    ARRAY['A2'],
    'medium',
    'El mantenimiento preventivo de una motocicleta busca principalmente:',
    'Detectar y corregir condiciones que puedan afectar su seguridad.',
    'Aumentar siempre la velocidad.',
    'Eliminar la necesidad de revisar los frenos.',
    'Reducir la visibilidad.',
    'A',
    'El mantenimiento preventivo permite conservar las condiciones de seguridad del vehículo.',
    'Seguridad vial',
    'Mantenimiento preventivo',
    'Referencia formativa ANSV'
),
(
    'knowledge',
    'vehicle',
    ARRAY['A2'],
    'easy',
    'El casco para motociclista debe utilizarse:',
    'Como elemento de protección durante la conducción.',
    'Únicamente cuando llueve.',
    'Solo en carretera.',
    'Únicamente cuando existe vigilancia.',
    'A',
    'El uso del casco forma parte de las medidas de seguridad exigibles para motociclistas.',
    'Ley 769 de 2002',
    'Artículo 94',
    'Código Nacional de Tránsito'
);
